default_chain: STRIDE
chains:
  STRIDE:
    key: STRIDE
    chain-id: STRIDE-TESTNET-4
    rpc-addr: http://62.171.173.206:16657
    grpc-addr: http://62.171.173.206:16090
    account-prefix: stride
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.01ustrd
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
  GAIA:
    key: GAIA
    chain-id: GAIA
    rpc-addr: http://78.107.234.44:36657
    grpc-addr: http://78.107.234.44:9797
    account-prefix: cosmos
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.01uatom
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
cl: {}
